version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: localdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432 # make sure you don't have another container running on 5432

volumes:
  postgres_data:
#postgresql://admin:admin@localhost:5432/localdb
